---
- hosts: all

  become: true
  tasks:
    - name: Hold specific packages
      apt:
        name: "{{ item }}"
        state: hold
      loop:
        - containerd
        - kubeadm
        - kubectl
        - kubelet

    - name: Update apt packages
      apt:
        upgrade: yes
        update_cache: yes
