---
- hosts: all

  become: true
  tasks:
    - name: Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Hold kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: Hold containerd
      ansible.builtin.dpkg_selections:
        name: containerd
        selection: hold

    - name: Hold kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

    - name: Update apt packages
      apt:
        upgrade: yes
        update_cache: yes
