---
- hosts: all

  become: true
  tasks:
    - name: Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold
        
    - name: Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Update apt packages
      apt:
        upgrade: yes
        update_cache: yes
